# Generated by Django 5.2.4 on 2026-01-20 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้จัดจำหน่าย')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='ผู้ติดต่อ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ผู้จัดจำหน่าย',
                'verbose_name_plural': 'ผู้จัดจำหน่าย',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่จ่าย')),
                ('category', models.CharField(choices=[('utilities', 'ค่าน้ำ-ค่าไฟ'), ('rent', 'ค่าเช่า'), ('salary', 'เงินเดือน'), ('maintenance', 'ค่าซ่อมบำรุง'), ('other', 'อื่นๆ')], max_length=100, verbose_name='ประเภท')),
                ('description', models.CharField(max_length=200, verbose_name='รายละเอียด')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'รายจ่าย',
                'verbose_name_plural': 'รายจ่าย',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสสินค้า')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วย')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาทุน')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('min_stock', models.IntegerField(default=10, verbose_name='จำนวนขั้นต่ำ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบสั่งซื้อ')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สั่งซื้อ')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับสินค้า')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม')),
                ('status', models.CharField(choices=[('pending', 'รอรับสินค้า'), ('received', 'รับสินค้าแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='ผู้จัดจำหน่าย')),
            ],
            options={
                'verbose_name': 'การนำเข้าสินค้า',
                'verbose_name_plural': 'การนำเข้าสินค้า',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ราคารวม')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='สินค้า')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='ใบสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รายการสินค้านำเข้า',
                'verbose_name_plural': 'รายการสินค้านำเข้า',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบเสร็จ')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ขาย')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อลูกค้า')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนลด')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดสุทธิ')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอนเงิน'), ('card', 'บัตรเครดิต')], default='cash', max_length=20, verbose_name='วิธีชำระเงิน')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'การขายสินค้า',
                'verbose_name_plural': 'การขายสินค้า',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ราคารวม')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='สินค้า')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale', verbose_name='ใบเสร็จ')),
            ],
            options={
                'verbose_name': 'รายการสินค้าขาย',
                'verbose_name_plural': 'รายการสินค้าขาย',
            },
        ),
    ]
